// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoGdztTALRD6FDv7KU3DzhEnliJZCh9Bg',
    appId: '1:1253344261:web:db69679649a9e59218886c',
    messagingSenderId: '1253344261',
    projectId: 'e-commerce-488c4',
    authDomain: 'e-commerce-488c4.firebaseapp.com',
    storageBucket: 'e-commerce-488c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cyrGk8N6f_djjWhBw9691U_zWMXMdmI',
    appId: '1:1253344261:android:97161fb7f8f71e8f18886c',
    messagingSenderId: '1253344261',
    projectId: 'e-commerce-488c4',
    storageBucket: 'e-commerce-488c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOorclD3V0py6REx0RL8ya_h82_VQ-iKg',
    appId: '1:1253344261:ios:69836f365160097518886c',
    messagingSenderId: '1253344261',
    projectId: 'e-commerce-488c4',
    storageBucket: 'e-commerce-488c4.firebasestorage.app',
    iosBundleId: 'com.example.juniorflutterroadmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOorclD3V0py6REx0RL8ya_h82_VQ-iKg',
    appId: '1:1253344261:ios:69836f365160097518886c',
    messagingSenderId: '1253344261',
    projectId: 'e-commerce-488c4',
    storageBucket: 'e-commerce-488c4.firebasestorage.app',
    iosBundleId: 'com.example.juniorflutterroadmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoGdztTALRD6FDv7KU3DzhEnliJZCh9Bg',
    appId: '1:1253344261:web:3838eac0fb0b487118886c',
    messagingSenderId: '1253344261',
    projectId: 'e-commerce-488c4',
    authDomain: 'e-commerce-488c4.firebaseapp.com',
    storageBucket: 'e-commerce-488c4.firebasestorage.app',
  );
}
